services:
  - type: web
    name: registration-ia-laravel
    env: docker # 👈 Le dice a Render que ignore sus entornos nativos y use tu Dockerfile
    plan: free
    region: oregon # Podés cambiarla por la región que prefieras (oregon, frankfurt, singapore, ohio)
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      # Render requiere que el contenedor escuche en el puerto que te asigna o mapear el tuyo estático.
      # Como tu Dockerfile expone el 8080, le avisamos a Render:
      - key: PORT
        value: "8080"